name: geojson
description: GeoJson classes using JsonSerializable
version: 1.0.2
# homepage: https://www.example.com
publish_to: 'none'

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  collection: ^1.18.0
  json_annotation: ^4.8.1

dev_dependencies:
  analyzer: ^6.3.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  lints: ^3.0.0
  recase: ^4.1.0
  test: ^1.25.0
