name: geojson
description: GeoJson classes using JsonSerializable
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.0 <3.0.0'


dependencies:
  json_annotation: ^4.4.0

dev_dependencies:
  analyzer: ^3.4.1
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  lints: ^1.0.1
  recase: ^4.0.0
  test: ^1.20.2
