name: geojson
description: GeoJson classes using JsonSerializable
version: 1.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  collection: ^1.18.0
  json_annotation: ^4.8.1

dev_dependencies:
  analyzer: ^6.1.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^2.1.1
  recase: ^4.1.0
  test: ^1.24.6
